# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='meter.proto',
  package='energy_meter',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmeter.proto\x12\x0c\x65nergy_meter\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n\x05Meter\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05value\x18\x02 \x01(\x01\"\x82\x01\n\tMeterList\x12)\n\x05start\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12!\n\x04list\x18\x03 \x03(\x0b\x32\x13.energy_meter.Meter2]\n\x12MeasurementService\x12G\n\x11GetServerResponse\x12\x17.energy_meter.MeterList\x1a\x17.energy_meter.MeterList\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_METER = _descriptor.Descriptor(
  name='Meter',
  full_name='energy_meter.Meter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='energy_meter.Meter.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='energy_meter.Meter.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=126,
)


_METERLIST = _descriptor.Descriptor(
  name='MeterList',
  full_name='energy_meter.MeterList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='energy_meter.MeterList.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='energy_meter.MeterList.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='list', full_name='energy_meter.MeterList.list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=259,
)

_METER.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_METERLIST.fields_by_name['start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_METERLIST.fields_by_name['end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_METERLIST.fields_by_name['list'].message_type = _METER
DESCRIPTOR.message_types_by_name['Meter'] = _METER
DESCRIPTOR.message_types_by_name['MeterList'] = _METERLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Meter = _reflection.GeneratedProtocolMessageType('Meter', (_message.Message,), {
  'DESCRIPTOR' : _METER,
  '__module__' : 'meter_pb2'
  # @@protoc_insertion_point(class_scope:energy_meter.Meter)
  })
_sym_db.RegisterMessage(Meter)

MeterList = _reflection.GeneratedProtocolMessageType('MeterList', (_message.Message,), {
  'DESCRIPTOR' : _METERLIST,
  '__module__' : 'meter_pb2'
  # @@protoc_insertion_point(class_scope:energy_meter.MeterList)
  })
_sym_db.RegisterMessage(MeterList)



_MEASUREMENTSERVICE = _descriptor.ServiceDescriptor(
  name='MeasurementService',
  full_name='energy_meter.MeasurementService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=261,
  serialized_end=354,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetServerResponse',
    full_name='energy_meter.MeasurementService.GetServerResponse',
    index=0,
    containing_service=None,
    input_type=_METERLIST,
    output_type=_METERLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEASUREMENTSERVICE)

DESCRIPTOR.services_by_name['MeasurementService'] = _MEASUREMENTSERVICE

# @@protoc_insertion_point(module_scope)
